version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: setgen_app
    command: python app.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: setgen_db
    environment:
      POSTGRES_DB: setlistdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
